# Generated by Django 4.2.5 on 2023-09-14 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import upload_files.models
import upload_files.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=150)),
                ('cash_model', models.CharField(max_length=50)),
                ('cash_number', models.CharField(max_length=50)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('old_os', models.CharField(blank=True, max_length=50, null=True)),
                ('new_os', models.CharField(blank=True, max_length=50, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('aes_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ταμειακές',
                'verbose_name_plural': 'Ταμειακές',
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=upload_files.models.client_directory_path, validators=[upload_files.validators.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_files.cash')),
            ],
        ),
    ]
