# Generated by Django 4.2.5 on 2023-10-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_file', models.FileField(upload_to='master_files/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_files.cash')),
            ],
        ),
        migrations.CreateModel(
            name='SubFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_file', models.FileField(upload_to='sub_files/')),
                ('master_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_files.masterfile')),
            ],
        ),
    ]
