# Generated by Django 4.2.5 on 2023-10-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0002_masterfile_subfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='subfile',
            name='title',
        ),
    ]
