# Generated by Django 4.2.5 on 2023-10-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0003_customer_remove_subfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_files.customer'),
        ),
    ]
