# Generated by Django 4.2.5 on 2023-09-21 05:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=150)),
                ('old_os', models.CharField(blank=True, max_length=50, null=True)),
                ('new_os', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Ταμειακές',
                'verbose_name_plural': 'Ταμειακές',
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_os', models.CharField(max_length=100)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.cash')),
            ],
        ),
    ]
