# Generated by Django 4.2.5 on 2023-09-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelB',
            new_name='Update',
        ),
    ]
