# Generated by Django 4.2.5 on 2023-09-21 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_rename_modelb_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='update',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
