# Generated by Django 4.2.5 on 2023-09-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_update_created_at_update_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='CashUpdate',
        ),
    ]
