# Generated by Django 4.2.5 on 2023-10-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_rename_update_cashupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='checkbox_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
    ]
